// `.astro/content-assets.mjs` is generated by `astro sync` and maps every image referenced from
// content frontmatter or markdown to the asset Astro emits for it. It is the only lookup that
// resolves the two reference styles used in this repo (`@images/…` and `../../images/…`) without
// importing the whole `src/images` tree, which would emit ~350 unused files into the build.
import contentAssetMap from "../../.astro/content-assets.mjs";

// Keys look like `@images/posts/2022/12/vernis.jpg?astroContentImageFlag=&importer=<md path>`.
// Both content collections sit one level deep, so a reference resolves to the same file whichever
// entry imported it, and the importer suffix can be dropped.
const byReference = new Map();
for (const [key, value] of contentAssetMap.entries()) {
  const reference = key.split("?")[0];
  if (value && !byReference.has(reference)) byReference.set(reference, value);
}

/** Resolve a markdown image reference to its ImageMetadata, or undefined. */
export function getContentImage(reference) {
  return byReference.get(reference);
}
