// src/pages/open-graph/[...route].ts
import { getCollection } from "astro:content";
import { OGImageRoute } from "astro-og-canvas";
import contentAssetMap from "../../../.astro/content-assets.mjs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(
  fileURLToPath(new URL("../../..", import.meta.url))
);

// `.astro/content-assets.mjs` is generated by `astro sync` and ships no type declarations.
const assetMap = contentAssetMap as unknown as Map<string, ImageMetadata>;

const collectionEntries = await getCollection("posts");

// Map the array of content collection entries to create an object.
// Converts [{ id: 'post.md', data: { title: 'Example', description: '' } }]
// to { 'post.md': { title: 'Example', description: '' } }
const pages = {
  // Site-wide card at /og/home.png, used as the default for pages without their own OG image.
  // `preview`/`previewPath` are spelled out so this entry matches the posts' shape for TS.
  home: {
    title: "Things done, by Simon.",
    description: "Mostly experiments, occasionally finished.",
    preview: undefined,
    previewPath: undefined,
  },
  ...Object.fromEntries(
    collectionEntries.map(({ id, data }) => [
      id,
      {
        ...data,
        // Keep the resolved absolute file path for the preview image so OG generation can read it from disk.
        previewPath: resolveContentImagePath(data.preview?.src),
      },
    ])
  ),
};

export const { getStaticPaths, GET } = await OGImageRoute({
  // A collection of pages to generate images for.
  // The keys of this object are used to generate the path for that image.
  // In this example, we generate one image at `/open-graph/example.png`.
  pages: pages,

  // For each page, this callback will be used to customize the OpenGraph image.
  getImageOptions: (routePath, page) => {
    const logoPath = page.previewPath;

    if (!logoPath && page.preview) {
      console.warn("No preview image path resolved for", routePath);
    }

    return {
      title: page.title,
      description: page.description,
      logo: logoPath
        ? {
            path: logoPath,
            size: [400],
          }
        : undefined,
      // The home card mirrors the site's signature: cream headline on the brand blue
      // (--blue / --on-blue from src/css/tokens.css, converted to sRGB).
      ...(routePath === "home" && {
        bgGradient: [[23, 104, 199]] as [number, number, number][],
        font: {
          title: { color: [251, 253, 255] as [number, number, number] },
          description: { color: [251, 253, 255] as [number, number, number] },
        },
      }),
    };
  },
});

function resolveContentImagePath(src: string | undefined) {
  if (!src) return undefined;

  for (const [key, value] of assetMap.entries()) {
    if (value?.src !== src) continue;

    const [assetPath, query] = key.split("?");
    const importer = query
      ? new URLSearchParams(query).get("importer")
      : undefined;

    // Resolve @images alias and relative paths against the importer file.
    const normalizedAssetPath = assetPath.startsWith("@images/")
      ? assetPath.replace(/^@images\//, "src/images/")
      : assetPath;

    const baseDir = importer ? path.dirname(importer) : projectRoot;
    const absolutePath = path.resolve(
      projectRoot,
      baseDir,
      normalizedAssetPath
    );
    return absolutePath;
  }

  return undefined;
}
